# Generated by Django 3.2 on 2022-03-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
