# Generated by Django 3.2 on 2022-03-22 06:09

from django.db import migrations, models
import recharge.models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0002_person_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='transaction',
            field=models.CharField(default=recharge.models.tns, max_length=15),
        ),
    ]
